/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as GuidesDevsecopsPipelineRouteImport } from './routes/guides.devsecops-pipeline'
import { Route as GuidesDevsecopsToolsRouteImport } from './routes/guides.devsecops-tools'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesDevsecopsPipelineRoute = GuidesDevsecopsPipelineRouteImport.update({
  id: '/guides/devsecops-pipeline',
  path: '/guides/devsecops-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesDevsecopsToolsRoute = GuidesDevsecopsToolsRouteImport.update({
  id: '/guides/devsecops-tools',
  path: '/guides/devsecops-tools',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/thank-you': typeof ThankYouRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/devsecops-pipeline': typeof GuidesDevsecopsPipelineRoute
  '/guides/devsecops-tools': typeof GuidesDevsecopsToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/thank-you': typeof ThankYouRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/devsecops-pipeline': typeof GuidesDevsecopsPipelineRoute
  '/guides/devsecops-tools': typeof GuidesDevsecopsToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/thank-you': typeof ThankYouRoute
  '/api/chat': typeof ApiChatRoute
  '/guides/devsecops-pipeline': typeof GuidesDevsecopsPipelineRoute
  '/guides/devsecops-tools': typeof GuidesDevsecopsToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resume'
    | '/thank-you'
    | '/api/chat'
    | '/guides/devsecops-pipeline'
    | '/guides/devsecops-tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resume'
    | '/thank-you'
    | '/api/chat'
    | '/guides/devsecops-pipeline'
    | '/guides/devsecops-tools'
  id:
    | '__root__'
    | '/'
    | '/resume'
    | '/thank-you'
    | '/api/chat'
    | '/guides/devsecops-pipeline'
    | '/guides/devsecops-tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumeRoute: typeof ResumeRoute
  ThankYouRoute: typeof ThankYouRoute
  ApiChatRoute: typeof ApiChatRoute
  GuidesDevsecopsPipelineRoute: typeof GuidesDevsecopsPipelineRoute
  GuidesDevsecopsToolsRoute: typeof GuidesDevsecopsToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/devsecops-pipeline': {
      id: '/guides/devsecops-pipeline'
      path: '/guides/devsecops-pipeline'
      fullPath: '/guides/devsecops-pipeline'
      preLoaderRoute: typeof GuidesDevsecopsPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/devsecops-tools': {
      id: '/guides/devsecops-tools'
      path: '/guides/devsecops-tools'
      fullPath: '/guides/devsecops-tools'
      preLoaderRoute: typeof GuidesDevsecopsToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumeRoute: ResumeRoute,
  ThankYouRoute: ThankYouRoute,
  ApiChatRoute: ApiChatRoute,
  GuidesDevsecopsPipelineRoute: GuidesDevsecopsPipelineRoute,
  GuidesDevsecopsToolsRoute: GuidesDevsecopsToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
