/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAiChatRouteImport } from './routes/dashboard.ai-chat'
import { Route as DashboardCicdRouteImport } from './routes/dashboard.cicd'
import { Route as DashboardGithubRouteImport } from './routes/dashboard.github'
import { Route as DashboardHealthRouteImport } from './routes/dashboard.health'
import { Route as DashboardLoginRouteImport } from './routes/dashboard.login'
import { Route as DashboardPerformanceRouteImport } from './routes/dashboard.performance'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardResetPasswordRouteImport } from './routes/dashboard.reset-password'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSignupRouteImport } from './routes/dashboard.signup'
import { Route as GuidesDevsecopsPipelineRouteImport } from './routes/guides.devsecops-pipeline'
import { Route as GuidesDevsecopsToolsRouteImport } from './routes/guides.devsecops-tools'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiChatRoute = DashboardAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCicdRoute = DashboardCicdRouteImport.update({
  id: '/cicd',
  path: '/cicd',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGithubRoute = DashboardGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHealthRoute = DashboardHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerformanceRoute = DashboardPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResetPasswordRoute = DashboardResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSignupRoute = DashboardSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => DashboardRoute,
} as any)
const GuidesDevsecopsPipelineRoute = GuidesDevsecopsPipelineRouteImport.update({
  id: '/guides/devsecops-pipeline',
  path: '/guides/devsecops-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesDevsecopsToolsRoute = GuidesDevsecopsToolsRouteImport.update({
  id: '/guides/devsecops-tools',
  path: '/guides/devsecops-tools',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/resume': typeof ResumeRoute
  '/thank-you': typeof ThankYouRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/ai-chat': typeof DashboardAiChatRoute
  '/dashboard/cicd': typeof DashboardCicdRoute
  '/dashboard/github': typeof DashboardGithubRoute
  '/dashboard/health': typeof DashboardHealthRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/reset-password': typeof DashboardResetPasswordRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/signup': typeof DashboardSignupRoute
  '/guides/devsecops-pipeline': typeof GuidesDevsecopsPipelineRoute
  '/guides/devsecops-tools': typeof GuidesDevsecopsToolsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/thank-you': typeof ThankYouRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/ai-chat': typeof DashboardAiChatRoute
  '/dashboard/cicd': typeof DashboardCicdRoute
  '/dashboard/github': typeof DashboardGithubRoute
  '/dashboard/health': typeof DashboardHealthRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/reset-password': typeof DashboardResetPasswordRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/signup': typeof DashboardSignupRoute
  '/guides/devsecops-pipeline': typeof GuidesDevsecopsPipelineRoute
  '/guides/devsecops-tools': typeof GuidesDevsecopsToolsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/resume': typeof ResumeRoute
  '/thank-you': typeof ThankYouRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/ai-chat': typeof DashboardAiChatRoute
  '/dashboard/cicd': typeof DashboardCicdRoute
  '/dashboard/github': typeof DashboardGithubRoute
  '/dashboard/health': typeof DashboardHealthRoute
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/reset-password': typeof DashboardResetPasswordRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/signup': typeof DashboardSignupRoute
  '/guides/devsecops-pipeline': typeof GuidesDevsecopsPipelineRoute
  '/guides/devsecops-tools': typeof GuidesDevsecopsToolsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/resume'
    | '/thank-you'
    | '/api/chat'
    | '/dashboard/ai-chat'
    | '/dashboard/cicd'
    | '/dashboard/github'
    | '/dashboard/health'
    | '/dashboard/login'
    | '/dashboard/performance'
    | '/dashboard/reports'
    | '/dashboard/reset-password'
    | '/dashboard/settings'
    | '/dashboard/signup'
    | '/guides/devsecops-pipeline'
    | '/guides/devsecops-tools'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resume'
    | '/thank-you'
    | '/api/chat'
    | '/dashboard/ai-chat'
    | '/dashboard/cicd'
    | '/dashboard/github'
    | '/dashboard/health'
    | '/dashboard/login'
    | '/dashboard/performance'
    | '/dashboard/reports'
    | '/dashboard/reset-password'
    | '/dashboard/settings'
    | '/dashboard/signup'
    | '/guides/devsecops-pipeline'
    | '/guides/devsecops-tools'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/resume'
    | '/thank-you'
    | '/api/chat'
    | '/dashboard/ai-chat'
    | '/dashboard/cicd'
    | '/dashboard/github'
    | '/dashboard/health'
    | '/dashboard/login'
    | '/dashboard/performance'
    | '/dashboard/reports'
    | '/dashboard/reset-password'
    | '/dashboard/settings'
    | '/dashboard/signup'
    | '/guides/devsecops-pipeline'
    | '/guides/devsecops-tools'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ResumeRoute: typeof ResumeRoute
  ThankYouRoute: typeof ThankYouRoute
  ApiChatRoute: typeof ApiChatRoute
  GuidesDevsecopsPipelineRoute: typeof GuidesDevsecopsPipelineRoute
  GuidesDevsecopsToolsRoute: typeof GuidesDevsecopsToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-chat': {
      id: '/dashboard/ai-chat'
      path: '/ai-chat'
      fullPath: '/dashboard/ai-chat'
      preLoaderRoute: typeof DashboardAiChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cicd': {
      id: '/dashboard/cicd'
      path: '/cicd'
      fullPath: '/dashboard/cicd'
      preLoaderRoute: typeof DashboardCicdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/github': {
      id: '/dashboard/github'
      path: '/github'
      fullPath: '/dashboard/github'
      preLoaderRoute: typeof DashboardGithubRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/health': {
      id: '/dashboard/health'
      path: '/health'
      fullPath: '/dashboard/health'
      preLoaderRoute: typeof DashboardHealthRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/performance': {
      id: '/dashboard/performance'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof DashboardPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reset-password': {
      id: '/dashboard/reset-password'
      path: '/reset-password'
      fullPath: '/dashboard/reset-password'
      preLoaderRoute: typeof DashboardResetPasswordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/signup': {
      id: '/dashboard/signup'
      path: '/signup'
      fullPath: '/dashboard/signup'
      preLoaderRoute: typeof DashboardSignupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/guides/devsecops-pipeline': {
      id: '/guides/devsecops-pipeline'
      path: '/guides/devsecops-pipeline'
      fullPath: '/guides/devsecops-pipeline'
      preLoaderRoute: typeof GuidesDevsecopsPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/devsecops-tools': {
      id: '/guides/devsecops-tools'
      path: '/guides/devsecops-tools'
      fullPath: '/guides/devsecops-tools'
      preLoaderRoute: typeof GuidesDevsecopsToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiChatRoute: typeof DashboardAiChatRoute
  DashboardCicdRoute: typeof DashboardCicdRoute
  DashboardGithubRoute: typeof DashboardGithubRoute
  DashboardHealthRoute: typeof DashboardHealthRoute
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardPerformanceRoute: typeof DashboardPerformanceRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardResetPasswordRoute: typeof DashboardResetPasswordRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSignupRoute: typeof DashboardSignupRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiChatRoute: DashboardAiChatRoute,
  DashboardCicdRoute: DashboardCicdRoute,
  DashboardGithubRoute: DashboardGithubRoute,
  DashboardHealthRoute: DashboardHealthRoute,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardPerformanceRoute: DashboardPerformanceRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardResetPasswordRoute: DashboardResetPasswordRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSignupRoute: DashboardSignupRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ResumeRoute: ResumeRoute,
  ThankYouRoute: ThankYouRoute,
  ApiChatRoute: ApiChatRoute,
  GuidesDevsecopsPipelineRoute: GuidesDevsecopsPipelineRoute,
  GuidesDevsecopsToolsRoute: GuidesDevsecopsToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
